'use client';
import {useEffect,useId,useState} from 'react';
import {Check,ChevronDown,Plus,X} from 'lucide-react';
import {countries,qualifications,parseQualifications} from './profile-options';
export function SearchSelect({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string;keywords?:string}[]}){
 const id=useId();const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[active,setActive]=useState(0);
 const selected=options.find(o=>o.value===value);const filtered=options.filter(o=>(o.label+' '+(o.keywords||'')).toLowerCase().includes(query.toLowerCase()));
 const choose=(v:string)=>{onChange(v);setOpen(false);setQuery('')};
 return <div className="field combo" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget)){setOpen(false);setQuery('')}}}><label htmlFor={id}>{label}</label><div className="combo-input"><input id={id} role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls={id+'-list'} aria-activedescendant={open&&filtered[active]?id+'-'+active:undefined} autoComplete="off" value={open?query:(selected?.label||value)} placeholder="Search and select…" onFocus={()=>{setQuery('');setActive(0);setOpen(true)}} onChange={e=>{setQuery(e.target.value);setActive(0);setOpen(true)}} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();if(!open){setOpen(true);setActive(0)}else setActive(a=>Math.min(a+1,filtered.length-1))}if(e.key==='ArrowUp'){e.preventDefault();setActive(a=>Math.max(0,a-1))}if(e.key==='Enter'&&open){e.preventDefault();if(filtered[active])choose(filtered[active].value)}if(e.key==='Escape'){setOpen(false);setQuery('')}}}/><ChevronDown size={16}/></div>{open&&<div className="combo-list" role="listbox" id={id+'-list'}>{filtered.map((o,i)=><button type="button" role="option" aria-selected={o.value===value} id={id+'-'+i} key={o.value} className={i===active?'highlight':''} ref={el=>{if(el&&i===active)el.scrollIntoView({block:'nearest'})}} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(o.value)}>{o.label}{o.value===value&&<Check size={16}/>}</button>)}{!filtered.length&&<p>No options found. Try a different search.</p>}</div>}</div>
}
export function CountrySelect({value,onChange}:{value:string;onChange:(v:string)=>void}){return <SearchSelect label="Country of school" value={value} onChange={onChange} options={countries.map(c=>({value:c.name,label:c.name,keywords:c.code+(c.code==='US'?' USA America':c.code==='GB'?' UK Britain':c.code==='KR'?' Korea':'')}))}/>}
export function QualificationFields({type,value,onChange}:{type:string;value:string;onChange:(v:string)=>void}){
 const parsed=parseQualifications(value);const rows=parsed||[];
 const change=(i:number,key:'subject'|'score',v:string)=>onChange(JSON.stringify(rows.map((r,j)=>j===i?{...r,[key]:v}:r)));
 return <fieldset className="qualification-group"><legend>{type}</legend>{parsed===null&&<div className="info-box"><p>Your saved results: {value}</p><button type="button" className="quiet" onClick={()=>onChange('[]')}>Use subject selections</button></div>}{rows.map((r,i)=><div className="qualification-row" key={i}><SearchSelect label={`${type} subject ${i+1}`} value={r.subject} onChange={v=>change(i,'subject',v)} options={[...qualifications[type],...(r.subject&&!qualifications[type].includes(r.subject)?[r.subject]:[])].filter(s=>s===r.subject||!rows.some(x=>x.subject===s)).map(s=>({value:s,label:s}))}/><label className="field"><span>Grade {i+1}</span><select value={r.score} onChange={e=>change(i,'score',e.target.value)}><option value="">Select grade</option>{(type==='AP'?['5','4','3','2','1','Not taken yet']:['A*','A','B','C','D','E','U','Not taken yet']).map(s=><option key={s}>{s}</option>)}</select></label><button className="icon-button" type="button" aria-label={`Remove ${type} subject ${i+1}`} onClick={()=>onChange(JSON.stringify(rows.filter((_,j)=>j!==i)))}><X size={16}/></button></div>)}{parsed!==null&&rows.length<12&&<button type="button" className="secondary" onClick={()=>onChange(JSON.stringify([...rows,{subject:'',score:''}]))}><Plus size={16}/> Add {type} subject</button>}<p className="helper">Select the subject and its result. Use the predicted grades checkbox below if applicable.</p></fieldset>
}
