// ISO 3166-1 country/territory codes; English display names from the runtime's CLDR data.
const codes='AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UM US UY UZ VA VC VE VG VI VN VU WF WS YE YT ZA ZM ZW'.split(' ');
const names=new Intl.DisplayNames(['en'],{type:'region'});
export const countries=codes.map(code=>({code,name:names.of(code)||code})).sort((a,b)=>a.name.localeCompare(b.name,'en'));
export const qualifications:Record<string,string[]>={
 AP:['African American Studies','Art History','Biology','Calculus AB','Calculus BC','Chemistry','Chinese Language and Culture','Comparative Government and Politics','Computer Science A','Computer Science Principles','English Language and Composition','English Literature and Composition','Environmental Science','European History','French Language and Culture','German Language and Culture','Human Geography','Italian Language and Culture','Japanese Language and Culture','Latin','Macroeconomics','Microeconomics','Music Theory','Physics 1','Physics 2','Physics C: Electricity and Magnetism','Physics C: Mechanics','Precalculus','Psychology','Research','Seminar','Spanish Language and Culture','Spanish Literature and Culture','Statistics','Studio Art: 2-D Art and Design','Studio Art: 3-D Art and Design','Studio Art: Drawing','United States Government and Politics','United States History','World History: Modern'],
 'A Levels':['Accounting','Art and Design','Biology','Business','Chemistry','Computer Science','Design and Technology','Drama and Theatre','Economics','English Language','English Literature','Environmental Management','French','Further Mathematics','Geography','German','History','Information Technology','Law','Mathematics','Media Studies','Music','Physical Education','Physics','Politics','Psychology','Religious Studies','Sociology','Spanish','Travel and Tourism'],
};
export type Qualification={subject:string;score:string};
export function parseQualifications(value:string):Qualification[]|null {try{const rows=JSON.parse(value);return Array.isArray(rows)&&rows.every(r=>typeof r.subject==='string'&&typeof r.score==='string')?rows:null}catch{return value===''?[]:null}}
export function qualificationError(type:string,value:string){if(!(type in qualifications))return '';const rows=parseQualifications(value);if(rows===null)return '';if(!rows.length)return `Add a ${type} subject or remove this qualification.`;if(rows.length>12)return 'Choose up to 12 subjects per qualification.';if(rows.some(r=>!r.subject||!r.score))return `Select a subject and grade for every ${type} row.`;if(new Set(rows.map(r=>r.subject)).size!==rows.length)return `Remove duplicate ${type} subjects.`;const scores=type==='AP'?['1','2','3','4','5','Not taken yet']:['A*','A','B','C','D','E','U','Not taken yet'];if(rows.some(r=>!scores.includes(r.score)))return `Select a valid ${type} grade.`;return ''}
