export type School={id:string;name:string;short:string;city:string;country:string;majors:string[];style:number;cost:number;color:string;url:string;note:string};
export const majors=['Computer Science','Business & Management','Economics','Engineering','Mathematics','Biology','Psychology','Political Science','International Relations','Philosophy','Literature','Art & Design','Physics','Neuroscience','Environmental Studies','Medicine & Health'];
// All matching attributes below are illustrative prototype data, not verified admissions facts.
export const schools:School[]=[
{id:'mit',name:'Massachusetts Institute of Technology',short:'MIT',city:'Cambridge, MA',country:'United States',majors:['Computer Science','Engineering','Mathematics','Physics'],style:0,cost:85000,color:'#b46873',url:'https://mitadmissions.org/',note:'Explore an environment built around technical inquiry and hands-on problem solving.'},
{id:'stanford',name:'Stanford University',short:'SU',city:'Stanford, CA',country:'United States',majors:['Computer Science','Engineering','Business & Management','Biology'],style:3,cost:90000,color:'#c7776d',url:'https://admission.stanford.edu/',note:'Investigate opportunities at the intersection of research, building, and entrepreneurship.'},
{id:'penn',name:'University of Pennsylvania',short:'PENN',city:'Philadelphia, PA',country:'United States',majors:['Business & Management','Economics','International Relations','Psychology'],style:3,cost:90000,color:'#719bda',url:'https://admissions.upenn.edu/',note:'Explore how your academic interests could connect with an interdisciplinary education.'},
{id:'chicago',name:'University of Chicago',short:'UChicago',city:'Chicago, IL',country:'United States',majors:['Economics','Mathematics','Philosophy','Political Science'],style:2,cost:90000,color:'#bb8098',url:'https://collegeadmissions.uchicago.edu/',note:'Consider a setting oriented toward asking difficult questions and examining ideas.'},
{id:'brown',name:'Brown University',short:'BROWN',city:'Providence, RI',country:'United States',majors:['Neuroscience','Literature','Philosophy','Art & Design','Computer Science'],style:2,cost:88000,color:'#bb9480',url:'https://admission.brown.edu/',note:'Explore how academic flexibility might support your combination of interests.'},
{id:'yale',name:'Yale University',short:'YALE',city:'New Haven, CT',country:'United States',majors:['Political Science','Literature','Philosophy','International Relations'],style:1,cost:88000,color:'#799ed9',url:'https://admissions.yale.edu/',note:'Investigate a broad education spanning the humanities, social sciences, and sciences.'},
{id:'princeton',name:'Princeton University',short:'PU',city:'Princeton, NJ',country:'United States',majors:['Mathematics','Physics','Economics','Political Science'],style:0,cost:85000,color:'#daa57a',url:'https://admission.princeton.edu/',note:'Explore undergraduate research and the academic questions you would pursue.'},
{id:'harvard',name:'Harvard University',short:'HU',city:'Cambridge, MA',country:'United States',majors:['Economics','Political Science','Biology','International Relations'],style:1,cost:90000,color:'#c47587',url:'https://college.harvard.edu/admissions',note:'Investigate how a broad liberal arts education could support your goals.'},
{id:'caltech',name:'California Institute of Technology',short:'CIT',city:'Pasadena, CA',country:'United States',majors:['Physics','Engineering','Mathematics','Computer Science'],style:0,cost:87000,color:'#dcb183',url:'https://www.admissions.caltech.edu/',note:'Explore an intensive scientific environment and whether it fits your preferred learning style.'},
{id:'rice',name:'Rice University',short:'RICE',city:'Houston, TX',country:'United States',majors:['Engineering','Computer Science','Biology','Economics'],style:0,cost:82000,color:'#7eabd1',url:'https://admission.rice.edu/',note:'Consider how research, community, and a residential campus could fit your priorities.'},
{id:'nyuad',name:'NYU Abu Dhabi',short:'NYUAD',city:'Abu Dhabi',country:'United Arab Emirates',majors:['Economics','Engineering','International Relations','Art & Design'],style:1,cost:85000,color:'#b896de',url:'https://nyuad.nyu.edu/en/admissions.html',note:'Investigate a global campus and the relationship between your interests and its programmes.'},
{id:'yonsei',name:'Yonsei University',short:'YU',city:'Seoul',country:'South Korea',majors:['Business & Management','Economics','International Relations','Biology'],style:1,cost:32000,color:'#6aa9df',url:'https://uic.yonsei.ac.kr/',note:'Review programme language, eligibility, and funding directly before shortlisting.'},
{id:'kaist',name:'KAIST',short:'KAIST',city:'Daejeon',country:'South Korea',majors:['Computer Science','Engineering','Physics','Mathematics'],style:0,cost:25000,color:'#80b8c5',url:'https://admission.kaist.ac.kr/intl-undergraduate/',note:'Explore technical programmes and verify the applicable international admissions route.'},
{id:'amherst',name:'Amherst College',short:'AC',city:'Amherst, MA',country:'United States',majors:['Literature','Philosophy','Psychology','Economics'],style:2,cost:85000,color:'#b6a0d4',url:'https://www.amherst.edu/admission',note:'Consider how a liberal arts setting could support exploration across disciplines.'},
{id:'asu',name:'Arizona State University',short:'ASU',city:'Tempe, AZ',country:'United States',majors:['Business & Management','Engineering','Computer Science','Art & Design','Environmental Studies'],style:3,cost:55000,color:'#d5a971',url:'https://admission.asu.edu/',note:'Investigate a broad programme selection and compare costs with your family budget.'},
{id:'utoronto',name:'University of Toronto',short:'UofT',city:'Toronto',country:'Canada',majors:['Computer Science','Biology','Psychology','Medicine & Health','Environmental Studies'],style:0,cost:68000,color:'#88b7b2',url:'https://future.utoronto.ca/',note:'Review campus and programme choices alongside international tuition and living expenses.'}
];
export const questions=[
{title:'An unsolved global problem lands on your desk. Where do you begin?',options:['Build a mathematical model to isolate the root cause.','Research the historical context, policies, and impact on people.','Question the assumptions: why is this considered a problem?','Build a prototype and test a practical solution.']},
{title:'Which kind of argument wins you over?',options:['A rigorous, step-by-step scientific or mathematical proof.','A well-researched policy debate or historical analysis.','A thoughtful discussion of ethical dilemmas and gray areas.','A convincing plan for innovation, growth, and real-world impact.']},
{title:'If you designed your education, what would it look like?',options:['A structured path toward deep technical expertise.','A shared core exploring great books and foundational ideas.','An open curriculum connecting very different disciplines.','A flexible mix of hands-on projects, internships, and building.']},
{title:'A free weekend on campus. What draws you in?',options:['A coding project, robotics competition, or research experiment.','Student government, Model UN, or the campus newspaper.','A long café conversation about art, philosophy, or economics.','A hackathon, founder meetup, or a startup project with friends.']},
{title:'Where can you picture yourself thriving?',options:['High-tech labs and collaborative spaces for solving hard problems.','Historic libraries, tradition, and the energy of a busy city.','Quiet quads and a community that loves exploring ideas.','Open spaces, makerspaces, and a culture of trying new things.']},
{title:'What do you most want to take away from university?',options:['The expertise to push my technical field forward.','A global network and the foundation for leadership.','The ability to think deeply and challenge assumptions.','The skills and confidence to build something that matters.']}
];
export const types=['The Investigator','The Changemaker','The Explorer','The Builder'];
export const efcs=['$0–$15,000','$15,001–$25,000','$25,001–$40,000','$40,001–$60,000','$60,001–$80,000','$80,001+'];
export type Profile={name:string;country:string;school:string;grade:string;majors:string[];gpa:string;scale:string;ielts:string;sat:string;extra:Record<string,string>;predicted:boolean;activities:string[];honors:{title:string;level:string}[];essay:string;answers:number[];dreams:string[];budget:string;destinations:string[];intake:string;consent:boolean;offers:boolean;email:string};
export const empty:Profile={name:'',country:'',school:'',grade:'',majors:[],gpa:'',scale:'4',ielts:'',sat:'',extra:{},predicted:false,activities:['','','','',''],honors:[{title:'',level:'School'}],essay:'',answers:Array(6).fill(-1),dreams:[],budget:'',destinations:['United States'],intake:'2027',consent:false,offers:false,email:''};
export function archetype(p:Profile){const counts=[0,0,0,0];p.answers.forEach(a=>{if(a>=0&&a<4)counts[a]++});return counts.indexOf(Math.max(...counts))}
export function rank(p:Profile){const b=[15000,25000,40000,60000,80000,100000][Number(p.budget)]||15000;return schools.map(s=>{const overlap=s.majors.filter(m=>p.majors.includes(m));const destination=p.destinations.includes(s.country);const affordable=s.cost<=b;const fit=Math.round(25+30*overlap.length/Math.max(1,p.majors.length)+(s.style===archetype(p)?20:5)+(destination?15:0)+(affordable?10:0));return {...s,fit,overlap,destination,affordable,gap:Math.max(0,s.cost-b)}}).sort((a,b)=>b.fit-a.fit)}
export function validate(p:Profile,step:number){if(step===0&&!p.name.trim())return 'Please enter your full name.';if(step===1&&(!p.country.trim()||!p.school.trim()||!p.grade))return 'Add your country, school, and grade.';if(step===2&&!p.majors.length)return 'Choose at least one major.';if(step===3){for(const [key,min,max] of [['gpa',0,Number(p.scale)],['ielts',0,9],['sat',400,1600]] as const){const v=p[key].trim();if(v.toUpperCase()==='N/A')continue;if(v===''||!Number.isFinite(Number(v))||Number(v)<min||Number(v)>max)return `Enter a valid ${key.toUpperCase()} (${min}–${max}) or N/A.`;if(key==='sat'&&Number(v)%10!==0)return 'SAT scores must be in increments of 10.';if(key==='ielts'&&Number(v)*2%1!==0)return 'IELTS scores must use half-band increments.';}for(const [k,v]of Object.entries(p.extra))if(!v.trim())return `Enter your ${k} results or N/A.`;}
if(step===4&&p.activities.slice(0,5).some(a=>!a.trim()))return 'Complete the five activity fields. You may write N/A where needed.';if(step>=7&&step<=12&&p.answers[step-7]<0)return 'Choose the answer that feels closest to you.';if(step===14&&(!p.budget||!p.destinations.length||!p.consent))return 'Choose your budget and destinations, then accept the required data consent.';return ''}
export const sample:Profile={...empty,name:'Alex Morgan',country:'Uzbekistan',school:'International School',grade:'11',majors:['Computer Science','Business & Management'],gpa:'3.8',ielts:'7',sat:'1450',activities:['Built a revision app used by 40 classmates.','Tutored 8 younger students in mathematics each week.','Led a school coding club with 15 members.','Volunteered 30 hours at a community library.','Organised a student fundraiser supporting 20 families.'],honors:[{title:'Regional mathematics competition finalist',level:'Regional'}],answers:[3,0,3,3,3,3],dreams:['stanford','penn'],budget:'0',consent:true};
