'use client';
import {useEffect,useState} from 'react';
import {CheckCircle2,ArrowRight} from 'lucide-react';
export default function EmailVerification({email,onEmailChange}:{email:string;onEmailChange:(v:string)=>void}){
 const [available,setAvailable]=useState<boolean|null>(null),[busy,setBusy]=useState(false),[challenge,setChallenge]=useState(''),[code,setCode]=useState(''),[verified,setVerified]=useState(''),[message,setMessage]=useState(''),[isError,setIsError]=useState(false),[cooldown,setCooldown]=useState(0);
 useEffect(()=>{let alive=true;fetch('/api/email').then(r=>r.json()).then((d:any)=>{if(alive)setAvailable(d.available===true)}).catch(()=>{if(alive)setAvailable(false)});return()=>{alive=false}},[]);
 useEffect(()=>{setChallenge('');setCode('');setVerified('');setMessage('')},[email]);
 useEffect(()=>{if(!cooldown)return;const timer=setTimeout(()=>setCooldown(s=>s-1),1000);return()=>clearTimeout(timer)},[cooldown]);
 async function submit(action:'send'|'verify') {setIsError(false);setMessage('');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())){setIsError(true);setMessage('Enter a valid email address.');return}setBusy(true);try{const res=await fetch('/api/email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,email,challengeId:challenge,code})});const data:any=await res.json();if(!res.ok)throw new Error(data.error||'Please try again.');if(action==='send'){setChallenge(data.challengeId);setCooldown(60);setMessage(data.message)}else{setVerified(data.email);setMessage('Email verified. You can now generate your assessment.')}}catch(e){setIsError(true);setMessage(e instanceof Error?e.message:'Connection failed. Please retry.')}finally{setBusy(false)}}
 if(available===null)return <p className="helper">Checking email availability…</p>;
 if(!available)return <p className="helper">No email is needed to view your assessment. Email verification is currently unavailable.</p>;
 return <div><label className="field"><span>Email address <small>Optional</small></span><input type="email" autoComplete="email" value={email} maxLength={250} placeholder="you@email.com" disabled={busy} onChange={e=>onEmailChange(e.target.value)}/></label>{verified===email.trim().toLowerCase()&&verified?<p className="email-verified"><CheckCircle2 size={20}/> Email verified</p>:<><p className="helper">We will send a one-time code to this address through our email provider. You can also continue without email.</p>{challenge&&<label className="field"><span>Six-digit verification code</span><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" autoComplete="one-time-code" maxLength={6} placeholder="000000"/></label>}<div className="email-actions">{challenge&&<button className="secondary" disabled={busy||code.length!==6} onClick={()=>submit('verify')}>{busy?'Checking…':'Verify email'}<ArrowRight size={16}/></button>}<button className="secondary" disabled={busy||cooldown>0} onClick={()=>submit('send')}>{cooldown?`Resend in ${cooldown}s`:busy?'Sending…':challenge?'Resend code':'Send verification code'}</button></div></>}{message&&<p className={isError?'form-error':'helper'} role={isError?'alert':'status'}>{message}</p>}</div>
}
