CREATE TABLE IF NOT EXISTS email_challenges (
 id TEXT PRIMARY KEY,
 email_hash TEXT NOT NULL UNIQUE,
 code_hash TEXT NOT NULL,
 expires INTEGER NOT NULL,
 attempts INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS email_limits (
 key TEXT PRIMARY KEY,
 count INTEGER NOT NULL,
 expires INTEGER NOT NULL
);
